name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          miniforge-version: 4.10.3-0

      - name: Create Conda environment
        run: |
          conda env create -f environment.yml
          conda activate PILOT

      - name: Install additional dependencies
        run: |
          conda run -n PILOT pip install pilotpy

      - name: Run tests
        run: |
          conda run -n PILOT pytest
