name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          miniforge-version: 4.10.3-0

      - name: Install dependencies
        run: |
          conda install python=3.11 r-base 
          pip install pilotpy

      - name: Run tests
        run: |
          pytest  
