name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          miniforge-version: 4.10.3-0

      - name: Create Conda environment
        run: |
          conda env create --name PILOT python=3.11.5 r-base --yes
          echo "conda activate PILOT" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install pilotpy
          pip install -r docs/requirements.txt

      - name: Run tests
        run: |
          conda activate PILOT
          pytest
